### ISSUE TITLE
HP Probook rules update

### ISSUE THREAD

**Issue by mortefer** [AJRepo/apparmor-skype#2]
Hey, thanks for the provided script
Here is a little bit of an update to it: HP Probook 450 generates similar message, but the rules for it will be a bit different:
before:  
`/sys/devices/*/*/*/power_supply/* r,`
after
 ```
/sys/devices/*/*/*/power_supply/* r,
 /sys/devices/*/*/power_supply/*/* r,
```
After that I stopped receiving the messages in dmesg

**Comment by AJRepo** [comment]
Thanks! Have added.
